export enum GENERAL_CODES {
  NOT_FOUND = "GENERAL.NOT_FOUND",
  INTERNAL = "GENERAL.INTERNAL",
  BAD_REQUEST = "GENERAL.BAD_REQUEST",
  VALIDATION = "GENERAL.VALIDATION",
  CONFLICT = "GENERAL.CONFLICT",
  UNAUTHORIZED = "GENERAL.UNAUTHORIZED",
  INVALID_REQUEST = "GENERAL.INVALID_REQUEST",
  OTP_FAILED = "GENERAL.OTP_FAILED",
  OTP_EXPIRED = "GENERAL.OTP_EXPIRED",
  TOKEN_EXPIRED = "GENERAL.TOKEN_EXPIRED",
  REQUEST_EXPIRED = "GENERAL.REQUEST_EXPIRED",
  OTP_ALREADY_SEND = "GENERAL.OTP_ALREADY_SEND",
}
